# Generated by Django 3.1.4 on 2021-02-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210210_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmark',
            name='profile_picture_url',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='profile',
            name='accessToken',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
