# Generated by Django 3.1.4 on 2021-02-11 07:24

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210210_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='pricing',
            field=models.ForeignKey(default=api.models.get_or_create_pricing, on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='api.pricing'),
        ),
    ]
