# Generated by Django 3.1.4 on 2021-02-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210211_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='hashtag',
            field=models.ManyToManyField(blank=True, to='api.Hashtag', verbose_name='ハッシュタグ'),
        ),
    ]
